nome = input('Qual é o seu nome completo? ')
ma = nome.upper()
mi = nome.lower()
to = len(nome.strip())
pri = len(nome.split()[0])
print ('Seu nome em maiúsculas é {}'.format(ma))
print ('Seu nome em minúsculas é {}'.format(mi))
print ('Seu nome completo tem {} letras'.format(to))
print ('Seu primeiro nome tem {} letras'.format(pri))